platform :ios, '9.3'
use_frameworks!

target 'TuringDI_Example' do
    pod 'TuringDIInterface', :path => '../../../'
  pod 'TuringDI', :path => '../../../'

  target 'TuringDI_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if [''].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
            else
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
            end
        end
    end
end
