platform :ios, '9.3'
use_frameworks!

target 'TuringValue_Example' do
  pod 'TuringValue', :path => '../../../'
  pod 'SwiftLint'

  target 'TuringValue_Tests' do
    inherit! :search_paths

    pod 'Device'
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if [''].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
      else
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
