use_frameworks!

target 'TuringErrorImplementation_Example' do
  pod 'TuringErrorImplementation', :path => '../'
  pod 'TuringErrorInterface', :path => '../../Interface/'

  target 'TuringErrorImplementation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if [''].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        else
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
            end
        end
    end
end
