use_frameworks!

target 'TuringErrorImplementation_Example' do
  pod 'TuringErrorImplementation', :path => '../'
  pod 'TuringErrorInterface', :path => '../../Interface/'

  target 'TuringErrorImplementation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
